baseURL = "https://stalinon.github.io/math-roadmap/"
languageCode = "ru"
title = 'Math Roadmap'
theme = "hugo-book"
publishDir = "public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true